Incoming
team-pandora/transfers-crud pull request #1
Opened 2022-07-12 14:21 UTC by sternomer

2022-07-14 09:15 UTC, MichaelSimkin requested changes
Things to do:
1) Route for getting multiple files (by filters)
2) Comments (in manager)
3) Tests

2022-07-26 07:28 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + */
Delete old lines ...

2022-07-26 07:32 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + * @param  fileId - id of current file .
formatting

```suggestion
 * @param fileId - id of current file.
```

2022-07-26 07:33 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + * @returns {Promise<IIncomingFile>} - Promise object containing the file with current id.
```suggestion
 * @returns {Promise<IIncomingFile>} Promise object containing the file with current id.
```

2022-07-26 07:36 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + * Get incoming file.
```suggestion
 * Get incoming File.
```

2022-07-26 07:36 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + * Create a new incoming file
```suggestion
 * Create a new incoming File.
```

2022-07-26 07:37 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> +
remove unneeded line

```suggestion
```

2022-07-26 07:40 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> +export const getMultipleFiles = async (query: any): Promise<IIncomingFile[]> => {
Why not name the function `getIncomingFiles`?

```suggestion
export const getIncomingFiles = async (query: any): Promise<IIncomingFile[]> => {
```

2022-07-26 07:41 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + * @returns {Promise<IIncomingFile[]>} - Promise object containing the filtered files.
```suggestion
 * @returns {Promise<IIncomingFile[]>} Promise object containing the filtered files.
```

2022-07-26 07:43 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> +export const getMultipleFiles = async (query: any): Promise<IIncomingFile[]> => {
query shouldn't be `any`. Set its type to `IIncomingFileFilters` and create it in interface.ts

2022-07-26 07:44 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + *
Add description.

2022-07-26 07:44 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + * @returns {IIncomingFile} - Promise object containing the deleted file
```suggestion
 * @returns {IIncomingFile} Promise object containing the deleted file.
```

2022-07-26 07:44 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> + * @param fileId - id of current file
```suggestion
 * @param fileId - id of current file.
```

2022-07-26 07:45 UTC, MichaelSimkin commented on src/express/incoming/manager.ts
> +
Delete unneeded line.
```suggestion
```

2022-07-26 07:49 UTC, MichaelSimkin commented on src/express/incoming/router.ts
> +    wrapMiddleware(incomingFileController.getMultipleFiles),
Change names:
```suggestion
    ValidateRequest(incomingValidator.getIncomingFilesRequestSchema),
    wrapMiddleware(incomingFileController.getIncomingFiles),
```

2022-07-26 07:51 UTC, MichaelSimkin commented on tests/incoming.test.ts
> +    const incomingFile = {
Add new line here.
```suggestion

    const incomingFile = {
```

2022-07-26 07:51 UTC, MichaelSimkin commented on tests/incoming.test.ts
> +    describe('get multiple files', () => {
Add new line

```suggestion

    describe('get multiple files', () => {
```

2022-07-26 07:52 UTC, MichaelSimkin commented on tests/incoming.test.ts
> +    describe('delete incoming file', () => {
Add new line.
```suggestion

    describe('delete incoming file', () => {
```

2022-07-26 07:53 UTC, MichaelSimkin commented on tests/incoming.test.ts
> +        it('should get all file and filter them', async () => {
```suggestion
        it('should get all files by filters', async () => {
```

2022-07-26 07:53 UTC, MichaelSimkin commented on tsconfig.json
> +    "lib": ["ES2021"],
What is this?

2022-07-26 11:40 UTC, sternomer commented on src/express/incoming/manager.ts
> + */
ok

2022-08-02 13:57 UTC, yarinBenisty approved these changes
nice!

2022-08-02 13:59 UTC, merged